name: Unit Tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - php/sqlcommenter-php/packages/sqlcommenter-laravel/**
      - php/sqlcommenter-php/samples/sqlcommenter-laravel/**
      - python/sqlcommenter-python/**
  pull_request:
    paths-ignore:
      - php/sqlcommenter-php/packages/sqlcommenter-laravel/**
      - php/sqlcommenter-php/samples/sqlcommenter-laravel/**
      - python/sqlcommenter-python/**
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
